apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-demo-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sulikoks/k8s-demo-config.git
    targetRevision: HEAD
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-demo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
