apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main-app
  name: main-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: main-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - image: sulikoks/k8s-demo:v1.0.23
          imagePullPolicy: IfNotPresent
          name: k8s-demo
          resources: {}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: DEMO_FAREWELL
              value: "Such a sweet sorrow"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
