apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2022-08-20T19:36:56Z"
  generation: 7
  labels:
    app: main-app
  name: main-app
  namespace: default
  resourceVersion: "189506"
  uid: b2e30778-a31c-438d-b29a-00f9a71e938c
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: main-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: main-app
    spec:
      containers:
        - image: sulikoks/k8s-demo:v1.0.9
          imagePullPolicy: IfNotPresent
          name: k8s-demo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
