apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main-app
  name: main-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: main-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - image: sulikoks/k8s-demo:v1.0.10
          imagePullPolicy: IfNotPresent
          name: k8s-demo
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
