apiVersion: v1
kind: Service
metadata:
  labels:
    app: main-app
  name: main-app
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30483
      port: 3030
      protocol: TCP
      targetPort: 3030
  selector:
    app: main-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
